num_1 = int(input('¬ведите первое число: '))
num_2 = int(input('¬ведите второе число: '))
print(num_1, 'умноженное на', num_2, 'равно', num_1 * num_2)
print(num_1, 'деленное на', num_2, 'равно', num_1 / num_2)
print(num_1, 'нацело деленное на', num_2, 'равно', num_1 // num_2)
print('ќстаток от делени€', num_1, 'на', num_2, 'равен', num_1 % num_2)
print(num_1, 'в степени', num_2, 'равно', num_1 * num_2)